const fs = require('fs');
let content = fs.readFileSync('app/dashboard/perencanaan/puk/create/page.tsx', 'utf8');
content = content.replace(/import Link from \'next\/link\';/, 'import Link from \'next/link\';\nimport Select from \'react-select\';');

const selectStyles = `styles={{
  control: (base) => ({ ...base, fontSize: 13, background: '#F8FAFC', borderColor: '#E2E8F0', minHeight: 38 }),
  menu: (base) => ({ ...base, zIndex: 9999 })
}}`;

content = content.replace(/<select \n\s*style=\{formInputStyle\}\n\s*value=\{form\.kdUpt\} \n\s*onChange=\{e => setForm\(\{\.\.\.form, kdUpt: e\.target\.value, nmUpt: e\.target\.options\[e\.target\.selectedIndex\]\.text\}\)\}\n\s*required\n\s*>\n\s*<option value=\"\">Pilih UPT\.\.\.<\/option>\n\s*\{upts\.map\(\(u: any\) => \(\n\s*<option key=\{u\.kd_upt\} value=\{u\.kd_upt\}>\{u\.nm_upt\}<\/option>\n\s*\)\)\}\n\s*<\/select>/g, 
`<Select options={[{value:'', label:'Pilih UPT...'}, ...upts.map((u: any) => ({value: u.kd_upt, label: u.nm_upt}))]} value={{value: form.kdUpt, label: form.nmUpt || 'Pilih UPT...'}} onChange={(e: any) => setForm({...form, kdUpt: e.value, nmUpt: e.label})} required ${selectStyles} />`);

content = content.replace(/<select \n\s*style=\{formInputStyle\}\n\s*value=\{form\.kdUkm\} \n\s*onChange=\{e => setForm\(\{\.\.\.form, kdUkm: e\.target\.value, nmUkm: e\.target\.options\[e\.target\.selectedIndex\]\.text\}\)\}\n\s*required\n\s*disabled=\{user\?\.role === \"superadmin\" && !form\.kdUpt\}\n\s*>\n\s*<option value=\"\">Pilih UKM\.\.\.<\/option>\n\s*\{ukms\.map\(\(u: any\) => \(\n\s*<option key=\{u\.kd_ukm\} value=\{u\.kd_ukm\}>\{u\.nm_ukm\}<\/option>\n\s*\)\)\}\n\s*<\/select>/g,
`<Select options={[{value:'', label:'Pilih UKM...'}, ...ukms.map((u: any) => ({value: u.kd_ukm, label: u.nm_ukm}))]} value={{value: form.kdUkm, label: form.nmUkm || 'Pilih UKM...'}} onChange={(e: any) => setForm({...form, kdUkm: e.value, nmUkm: e.label})} isDisabled={user?.role === 'superadmin' && !form.kdUpt} required ${selectStyles} />`);

content = content.replace(/<select style=\{formInputStyle\} value=\{form\.kdPeruntukan\} onChange=\{e => setForm\(\{\.\.\.form, kdPeruntukan: e\.target\.value, nmPeruntukan: e\.target\.options\[e\.target\.selectedIndex\]\.text, kdKomponen: \"\", nmKomponen: \"\", kdRincian: \"\", nmRincian: \"\"\}\)\} required disabled=\{user\?\.role === \"superadmin\" && !form\.kdUpt\}>\n\s*<option value=\"\">Pilih Peruntukan\.\.\.<\/option>\n\s*\{peruntukans\.map\(\(p: any\) => \(\<option key=\{p\.kd_peruntukan\} value=\{p\.kd_peruntukan\}>\{p\.nm_peruntukan\}<\/option>\)\)\}\n\s*<\/select>/g,
`<Select options={[{value:'', label:'Pilih Peruntukan...'}, ...peruntukans.map((p: any) => ({value: p.kd_peruntukan, label: p.nm_peruntukan}))]} value={{value: form.kdPeruntukan, label: form.nmPeruntukan || 'Pilih Peruntukan...'}} onChange={(e: any) => setForm({...form, kdPeruntukan: e.value, nmPeruntukan: e.label, kdKomponen: '', nmKomponen: '', kdRincian: '', nmRincian: ''})} isDisabled={user?.role === 'superadmin' && !form.kdUpt} required ${selectStyles} />`);

content = content.replace(/<select style=\{formInputStyle\} value=\{form\.kdKomponen\} onChange=\{e => setForm\(\{\.\.\.form, kdKomponen: e\.target\.value, nmKomponen: e\.target\.options\[e\.target\.selectedIndex\]\.text, kdRincian: \"\", nmRincian: \"\"\}\)\} required disabled=\{!form\.kdPeruntukan\}>\n\s*<option value=\"\">Pilih Komponen\.\.\.<\/option>\n\s*\{komponens\.map\(\(k: any\) => \(\<option key=\{k\.kd_komponen\} value=\{k\.kd_komponen\}>\{k\.nm_komponen\}<\/option>\)\)\}\n\s*<\/select>/g,
`<Select options={[{value:'', label:'Pilih Komponen...'}, ...komponens.map((k: any) => ({value: k.kd_komponen, label: k.nm_komponen}))]} value={{value: form.kdKomponen, label: form.nmKomponen || 'Pilih Komponen...'}} onChange={(e: any) => setForm({...form, kdKomponen: e.value, nmKomponen: e.label, kdRincian: '', nmRincian: ''})} isDisabled={!form.kdPeruntukan} required ${selectStyles} />`);

content = content.replace(/<select style=\{formInputStyle\} value=\{form\.kdRincian\} onChange=\{e => setForm\(\{\.\.\.form, kdRincian: e\.target\.value, nmRincian: e\.target\.options\[e\.target\.selectedIndex\]\.text\}\)\} required disabled=\{!form\.kdKomponen\}>\n\s*<option value=\"\">Pilih Rincian\.\.\.<\/option>\n\s*\{rincians\.map\(\(r: any\) => \(\<option key=\{r\.kd_rincian\} value=\{r\.kd_rincian\}>\{r\.nm_rincian\}<\/option>\)\)\}\n\s*<\/select>/g,
`<Select options={[{value:'', label:'Pilih Rincian...'}, ...rincians.map((r: any) => ({value: r.kd_rincian, label: r.nm_rincian}))]} value={{value: form.kdRincian, label: form.nmRincian || 'Pilih Rincian...'}} onChange={(e: any) => setForm({...form, kdRincian: e.value, nmRincian: e.label})} isDisabled={!form.kdKomponen} required ${selectStyles} />`);

content = content.replace(/<select style=\{formInputStyle\} value=\{form\.kdSubKegiatan\} onChange=\{e => setForm\(\{\.\.\.form, kdSubKegiatan: e\.target\.value, nmSubKegiatan: e\.target\.options\[e\.target\.selectedIndex\]\.text\}\)\} required>\n\s*<option value=\"\">Pilih Sub Kegiatan\.\.\.<\/option>\n\s*\{subkegiatans\.map\(\(s: any\) => \(\<option key=\{s\.kd_sub_kegiatan\} value=\{s\.kd_sub_kegiatan\}>\{s\.nm_sub_kegiatan\}<\/option>\)\)\}\n\s*<\/select>/g,
`<Select options={[{value:'', label:'Pilih Sub Kegiatan...'}, ...subkegiatans.map((s: any) => ({value: s.kd_sub_kegiatan, label: s.nm_sub_kegiatan}))]} value={{value: form.kdSubKegiatan, label: form.nmSubKegiatan || 'Pilih Sub Kegiatan...'}} onChange={(e: any) => setForm({...form, kdSubKegiatan: e.value, nmSubKegiatan: e.label})} required ${selectStyles} />`);

content = content.replace(/<select style=\{formInputStyle\} value=\{form\.kdSpm\} onChange=\{e => setForm\(\{\.\.\.form, kdSpm: e\.target\.value, nmSpm: e\.target\.options\[e\.target\.selectedIndex\]\.text\}\)\} required disabled=\{user\?\.role === \"superadmin\" && !form\.kdUpt\}>\n\s*<option value=\"\">Pilih SPM\.\.\.<\/option>\n\s*\{spms\.map\(\(s: any\) => \(\<option key=\{s\.kd_spm\} value=\{s\.kd_spm\}>\{s\.nm_spm\}<\/option>\)\)\}\n\s*<\/select>/g,
`<Select options={[{value:'', label:'Pilih SPM...'}, ...spms.map((s: any) => ({value: s.kd_spm, label: s.nm_spm}))]} value={{value: form.kdSpm, label: form.nmSpm || 'Pilih SPM...'}} onChange={(e: any) => setForm({...form, kdSpm: e.value, nmSpm: e.label})} isDisabled={user?.role === 'superadmin' && !form.kdUpt} required ${selectStyles} />`);

content = content.replace(/<select \n\s*style=\{formInputStyle\} \n\s*value=\{form\.sumdan\} \n\s*onChange=\{e => setForm\(\{\.\.\.form, sumdan: e\.target\.value\}\)\} \n\s*required\n\s*>\n\s*<option value=\"\">Pilih Sumber Dana\.\.\.<\/option>\n\s*\{sumdans\.map\(\(s: any\) => \(\n\s*<option key=\{s\.id \|\| s\.sumdan\} value=\{s\.sumdan\}>\{s\.sumdan\}<\/option>\n\s*\)\)\}\n\s*<\/select>/g,
`<Select options={[{value:'', label:'Pilih Sumber Dana...'}, ...sumdans.map((s: any) => ({value: s.sumdan, label: s.sumdan}))]} value={{value: form.sumdan, label: form.sumdan || 'Pilih Sumber Dana...'}} onChange={(e: any) => setForm({...form, sumdan: e.value})} required ${selectStyles} />`);

fs.writeFileSync('app/dashboard/perencanaan/puk/create/page.tsx', content);
console.log('Replaced create page successfully!');
